### ISSUE TITLE
Having errors when making the sample on Jetson TK1

### ISSUE THREAD

**Issue by ikimonogakari** [adujardin/zed-save-depth#1]
I compiled zed-save-depth on Jetson TK1 with L4T 21.4, and it shows that "/usr/bin/ld: cannot find -lopencv_dep_cudart".
I have installed camke 3.5.0, opencv 2.4.12 and CUDA 6.5.
I tried to modify the cuda_lib_path to /usr/local/cuda-6.5/target/armv7-linux-gnueabihf/lib/ in CMakeList.txt
but it didn't work.

**Comment by obraun-sl** [comment]
Hi,

Please use OpenCV4Tegra provided with the JetPack installation.
Best,
Olivier.
