### ISSUE TITLE
Doesn't compile with Zed SDK v.3.0.1; Is there a way to write out pointcloud with 3.0.1?

### ISSUE THREAD

**Issue by majinshaoyuindustry** [adujardin/zed-save-depth#17]
1>------ Build started: Project: ZERO_CHECK, Configuration: Release x64 ------
1>Checking Build System
2>------ Build started: Project: ZED_Save_depth, Configuration: Release x64 ------
2>Building Custom Rule D:/zed/zed-save-depth/CMakeLists.txt
2>cl : Command line warning D9002: ignoring unknown option '-std=c++0x'
2>cl : Command line warning D9002: ignoring unknown option '-g'
2>cl : Command line warning D9002: ignoring unknown option '-O3'
2>main.cpp
2>D:\zed\zed-save-depth\src\main.cpp(42): error C2039: 'POINT_CLOUD_FORMAT': is not a member of 'sl'
2>C:\Program Files (x86)\ZED SDK\include\sl/Camera.hpp(4825): note: see declaration of 'sl'
2>D:\zed\zed-save-depth\src\main.cpp(42): error C3646: 'PC_Format': unknown override specifier
2>D:\zed\zed-save-depth\src\main.cpp(42): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>D:\zed\zed-save-depth\src\main.cpp(43): error C2039: 'DEPTH_FORMAT': is not a member of 'sl'
2>C:\Program Files (x86)\ZED SDK\include\sl/Camera.hpp(4825): note: see declaration of 'sl'
2>D:\zed\zed-save-depth\src\main.cpp(43): error C3646: 'Depth_Format': unknown override specifier
2>D:\zed\zed-save-depth\src\main.cpp(43): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>D:\zed\zed-save-depth\src\main.cpp(53): error C2039: 'POINT_CLOUD_FORMAT': is not a member of 'sl'
2>C:\Program Files (x86)\ZED SDK\include\sl/Camera.hpp(4825): note: see declaration of 'sl'
2>D:\zed\zed-save-depth\src\main.cpp(53): error C2065: 'POINT_CLOUD_FORMAT': undeclared identifier
2>D:\zed\zed-save-depth\src\main.cpp(53): error C2146: syntax error: missing ')' before identifier 'f'
2>D:\zed\zed-save-depth\src\main.cpp(53): error C2143: syntax error: missing ';' before '{'
2>D:\zed\zed-save-depth\src\main.cpp(53): error C2447: '{': missing function header (old-style formal list?)
2>D:\zed\zed-save-depth\src\main.cpp(74): error C2039: 'DEPTH_FORMAT': is not a member of 'sl'
2>C:\Program Files (x86)\ZED SDK\include\sl/Camera.hpp(4825): note: see declaration of 'sl'
2>D:\zed\zed-save-depth\src\main.cpp(74): error C2065: 'DEPTH_FORMAT': undeclared identifier
2>D:\zed\zed-save-depth\src\main.cpp(74): error C2146: syntax error: missing ')' before identifier 'f'
2>D:\zed\zed-save-depth\src\main.cpp(74): error C2143: syntax error: missing ';' before '{'
2>D:\zed\zed-save-depth\src\main.cpp(74): error C2447: '{': missing function header (old-style formal list?)
2>D:\zed\zed-save-depth\src\main.cpp(96): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2>D:\zed\zed-save-depth\src\main.cpp(96): error C2146: syntax error: missing ';' before identifier 'CtrlHandler'
2>D:\zed\zed-save-depth\src\main.cpp(96): error C2143: syntax error: missing ';' before '{'
2>D:\zed\zed-save-depth\src\main.cpp(96): error C2447: '{': missing function header (old-style formal list?)
2>D:\zed\zed-save-depth\src\main.cpp(123): error C2039: 'getDepthMaxRangeValue': is not a member of 'sl::Camera'
2>C:\Program Files (x86)\ZED SDK\include\sl/Camera.hpp(5775): note: see declaration of 'sl::Camera'
2>D:\zed\zed-save-depth\src\main.cpp(125): error C2039: 'Depth_Format': is not a member of 'SaveParamStruct'
2>D:\zed\zed-save-depth\src\main.cpp(41): note: see declaration of 'SaveParamStruct'
2>D:\zed\zed-save-depth\src\main.cpp(125): error C3861: 'getFormatNameD': identifier not found
2>D:\zed\zed-save-depth\src\main.cpp(126): error C2039: 'saveDepthAs': is not a member of 'sl'
2>C:\Program Files (x86)\ZED SDK\include\sl/Camera.hpp(4825): note: see declaration of 'sl'
2>D:\zed\zed-save-depth\src\main.cpp(126): error C2039: 'Depth_Format': is not a member of 'SaveParamStruct'
2>D:\zed\zed-save-depth\src\main.cpp(41): note: see declaration of 'SaveParamStruct'
2>D:\zed\zed-save-depth\src\main.cpp(126): error C3861: 'saveDepthAs': identifier not found
2>D:\zed\zed-save-depth\src\main.cpp(132): error C2039: 'PC_Format': is not a member of 'SaveParamStruct'
2>D:\zed\zed-save-depth\src\main.cpp(41): note: see declaration of 'SaveParamStruct'
2>D:\zed\zed-save-depth\src\main.cpp(132): error C3861: 'getFormatNamePC': identifier not found
2>D:\zed\zed-save-depth\src\main.cpp(133): error C2039: 'savePointCloudAs': is not a member of 'sl'
2>C:\Program Files (x86)\ZED SDK\include\sl/Camera.hpp(4825): note: see declaration of 'sl'
2>D:\zed\zed-save-depth\src\main.cpp(133): error C2039: 'PC_Format': is not a member of 'SaveParamStruct'
2>D:\zed\zed-save-depth\src\main.cpp(41): note: see declaration of 'SaveParamStruct'
2>D:\zed\zed-save-depth\src\main.cpp(133): error C3861: 'savePointCloudAs': identifier not found
2>D:\zed\zed-save-depth\src\main.cpp(147): error C2039: 'VIEW_SIDE_BY_SIDE': is not a member of 'sl'
2>C:\Program Files (x86)\ZED SDK\include\sl/Camera.hpp(4825): note: see declaration of 'sl'
2>D:\zed\zed-save-depth\src\main.cpp(147): error C2065: 'VIEW_SIDE_BY_SIDE': undeclared identifier
2>D:\zed\zed-save-depth\src\main.cpp(156): error C2039: 'DEPTH_MODE_PERFORMANCE': is not a member of 'sl'
2>C:\Program Files (x86)\ZED SDK\include\sl/Camera.hpp(4825): note: see declaration of 'sl'
2>D:\zed\zed-save-depth\src\main.cpp(156): error C2065: 'DEPTH_MODE_PERFORMANCE': undeclared identifier
2>D:\zed\zed-save-depth\src\main.cpp(193): error C2039: 'svo_input_filename': is not a member of 'sl::InitParameters'
2>C:\Program Files (x86)\ZED SDK\include\sl/Camera.hpp(4867): note: see declaration of 'sl::InitParameters'
2>D:\zed\zed-save-depth\src\main.cpp(200): error C2039: 'DEPTH_MODE_PERFORMANCE': is not a member of 'sl'
2>C:\Program Files (x86)\ZED SDK\include\sl/Camera.hpp(4825): note: see declaration of 'sl'
2>D:\zed\zed-save-depth\src\main.cpp(200): error C2065: 'DEPTH_MODE_PERFORMANCE': undeclared identifier
2>D:\zed\zed-save-depth\src\main.cpp(204): error C2039: 'DEPTH_MODE_MEDIUM': is not a member of 'sl'
2>C:\Program Files (x86)\ZED SDK\include\sl/Camera.hpp(4825): note: see declaration of 'sl'
2>D:\zed\zed-save-depth\src\main.cpp(204): error C2065: 'DEPTH_MODE_MEDIUM': undeclared identifier
2>D:\zed\zed-save-depth\src\main.cpp(208): error C2039: 'DEPTH_MODE_QUALITY': is not a member of 'sl'
2>C:\Program Files (x86)\ZED SDK\include\sl/Camera.hpp(4825): note: see declaration of 'sl'
2>D:\zed\zed-save-depth\src\main.cpp(208): error C2065: 'DEPTH_MODE_QUALITY': undeclared identifier
2>D:\zed\zed-save-depth\src\main.cpp(212): error C2039: 'DEPTH_MODE_ULTRA': is not a member of 'sl'
2>C:\Program Files (x86)\ZED SDK\include\sl/Camera.hpp(4825): note: see declaration of 'sl'
2>D:\zed\zed-save-depth\src\main.cpp(212): error C2065: 'DEPTH_MODE_ULTRA': undeclared identifier
2>D:\zed\zed-save-depth\src\main.cpp(231): error C2039: 'UNIT_MILLIMETER': is not a member of 'sl'
2>C:\Program Files (x86)\ZED SDK\include\sl/Camera.hpp(4825): note: see declaration of 'sl'
2>D:\zed\zed-save-depth\src\main.cpp(231): error C2065: 'UNIT_MILLIMETER': undeclared identifier
2>D:\zed\zed-save-depth\src\main.cpp(239): error C2039: 'SUCCESS': is not a member of 'sl'
2>C:\Program Files (x86)\ZED SDK\include\sl/Camera.hpp(4825): note: see declaration of 'sl'
2>D:\zed\zed-save-depth\src\main.cpp(239): error C2065: 'SUCCESS': undeclared identifier
2>D:\zed\zed-save-depth\src\main.cpp(250): error C2065: 'PHANDLER_ROUTINE': undeclared identifier
2>D:\zed\zed-save-depth\src\main.cpp(250): error C2146: syntax error: missing ')' before identifier 'CtrlHandler'
2>D:\zed\zed-save-depth\src\main.cpp(250): error C3861: 'SetConsoleCtrlHandler': identifier not found
2>D:\zed\zed-save-depth\src\main.cpp(250): error C2146: syntax error: missing ';' before identifier 'CtrlHandler'
2>D:\zed\zed-save-depth\src\main.cpp(250): error C2065: 'CtrlHandler': undeclared identifier
2>D:\zed\zed-save-depth\src\main.cpp(250): error C2065: 'TRUE': undeclared identifier
2>D:\zed\zed-save-depth\src\main.cpp(250): error C2059: syntax error: ')'
2>D:\zed\zed-save-depth\src\main.cpp(267): error C2039: 'setDepthMaxRangeValue': is not a member of 'sl::Camera'
2>C:\Program Files (x86)\ZED SDK\include\sl/Camera.hpp(5775): note: see declaration of 'sl::Camera'
2>D:\zed\zed-save-depth\src\main.cpp(275): error C2039: 'PC_Format': is not a member of 'SaveParamStruct'
2>D:\zed\zed-save-depth\src\main.cpp(41): note: see declaration of 'SaveParamStruct'
2>D:\zed\zed-save-depth\src\main.cpp(275): error C2039: 'POINT_CLOUD_FORMAT': is not a member of 'sl'
2>C:\Program Files (x86)\ZED SDK\include\sl/Camera.hpp(4825): note: see declaration of 'sl'
2>D:\zed\zed-save-depth\src\main.cpp(275): error C2061: syntax error: identifier 'POINT_CLOUD_FORMAT'
2>D:\zed\zed-save-depth\src\main.cpp(276): error C2039: 'Depth_Format': is not a member of 'SaveParamStruct'
2>D:\zed\zed-save-depth\src\main.cpp(41): note: see declaration of 'SaveParamStruct'
2>D:\zed\zed-save-depth\src\main.cpp(276): error C2039: 'DEPTH_FORMAT': is not a member of 'sl'
2>C:\Program Files (x86)\ZED SDK\include\sl/Camera.hpp(4825): note: see declaration of 'sl'
2>D:\zed\zed-save-depth\src\main.cpp(276): error C2061: syntax error: identifier 'DEPTH_FORMAT'
2>D:\zed\zed-save-depth\src\main.cpp(294): error C2039: 'SENSING_MODE_STANDARD': is not a member of 'sl'
2>C:\Program Files (x86)\ZED SDK\include\sl/Camera.hpp(4825): note: see declaration of 'sl'
2>D:\zed\zed-save-depth\src\main.cpp(294): error C2065: 'SENSING_MODE_STANDARD': undeclared identifier
2>D:\zed\zed-save-depth\src\main.cpp(295): error C2039: 'VIEW_DEPTH': is not a member of 'sl'
2>C:\Program Files (x86)\ZED SDK\include\sl/Camera.hpp(4825): note: see declaration of 'sl'
2>D:\zed\zed-save-depth\src\main.cpp(295): error C2065: 'VIEW_DEPTH': undeclared identifier
2>D:\zed\zed-save-depth\src\main.cpp(297): error C2039: 'MEM_CPU': is not a member of 'sl'
2>C:\Program Files (x86)\ZED SDK\include\sl/Camera.hpp(4825): note: see declaration of 'sl'
2>D:\zed\zed-save-depth\src\main.cpp(297): error C2065: 'MEM_CPU': undeclared identifier
2>D:\zed\zed-save-depth\src\main.cpp(297): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
2>D:\zed\zed-save-depth\src\main.cpp(322): error C2039: 'PC_Format': is not a member of 'SaveParamStruct'
2>D:\zed\zed-save-depth\src\main.cpp(41): note: see declaration of 'SaveParamStruct'
2>D:\zed\zed-save-depth\src\main.cpp(322): error C2039: 'POINT_CLOUD_FORMAT': is not a member of 'sl'
2>C:\Program Files (x86)\ZED SDK\include\sl/Camera.hpp(4825): note: see declaration of 'sl'
2>D:\zed\zed-save-depth\src\main.cpp(322): error C2061: syntax error: identifier 'POINT_CLOUD_FORMAT'
2>D:\zed\zed-save-depth\src\main.cpp(323): error C2039: 'PC_Format': is not a member of 'SaveParamStruct'
2>D:\zed\zed-save-depth\src\main.cpp(41): note: see declaration of 'SaveParamStruct'
2>D:\zed\zed-save-depth\src\main.cpp(323): error C3861: 'getFormatNamePC': identifier not found
2>D:\zed\zed-save-depth\src\main.cpp(331): error C2039: 'Depth_Format': is not a member of 'SaveParamStruct'
2>D:\zed\zed-save-depth\src\main.cpp(41): note: see declaration of 'SaveParamStruct'
2>D:\zed\zed-save-depth\src\main.cpp(331): error C2039: 'DEPTH_FORMAT': is not a member of 'sl'
2>C:\Program Files (x86)\ZED SDK\include\sl/Camera.hpp(4825): note: see declaration of 'sl'
2>D:\zed\zed-save-depth\src\main.cpp(331): error C2061: syntax error: identifier 'DEPTH_FORMAT'
2>D:\zed\zed-save-depth\src\main.cpp(332): error C2039: 'Depth_Format': is not a member of 'SaveParamStruct'
2>D:\zed\zed-save-depth\src\main.cpp(41): note: see declaration of 'SaveParamStruct'
2>D:\zed\zed-save-depth\src\main.cpp(332): error C3861: 'getFormatNameD': identifier not found
2>Done building project "ZED_Save_depth.vcxproj" -- FAILED.
3>------ Skipped Build: Project: ALL_BUILD, Configuration: Release x64 ------
3>Project not selected to build for this solution configuration 
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 1 skipped ==========

**Comment by adujardin** [comment]
Yes you can use this example https://github.com/stereolabs/zed-opencv/tree/master/cpp

**Comment by majinshaoyuindustry** [comment]
> Yes you can use this example https://github.com/stereolabs/zed-opencv/tree/master/cpp

Thank you so much again for your fast and professional advice. I will use this one for now.
