### ISSUE TITLE
i have problem getting distance in z-direction from the depth map..

### ISSUE THREAD

**Issue by Hash17** [adujardin/zed-save-depth#4]
I tried to use retrieveMeasure(DEPTH) and retrieveMeasure(XYZ)....i dont know how to access the resulted matrix in order to get the distance in z-direction for a certain pixel..which one of these 2 functions are correct to do so and how to access the resulted matrix in order to get distance in z?

**Comment by obraun-sl** [comment]
Hi,

if you only want the depth on the Z axis, then you can use the retrieveMeasure(DEPTH) function.
To extract the depth value ( z)  for pixel (i,j) then you can do the following : 

```
sl::zed::Mat mdepth = zed->retrieveMeasure(DEPTH);
float* zBuffer = (float*) mdepth.data;
z =zBuffer[i+j*mdepth.step/sizeof(float)];
```

retrieveMeasure(XYZ) returns the (X,Y,Z) world coordinates in a 4channels float buffer.

Best,
/_OB_/

**Comment by Hash17** [comment]
well thanks alot Oliver...i just want to make sure i got this right 
1- the value returned to z is the distance in mm right?
2- what's the difference if I used retrieveMeasure(XYZ) ? would return the xyz and color of each pixel? and if yes then do you know how to extract x,y,z values of each pixel?

I know i asked alot but I really appreciate your help :D

**Comment by obraun-sl** [comment]
Hi,
1. Z value will be the distance in the unit you select during Init. In the InitParam structure, you can choose the Unit (structure entry)  between the available enum (mm, meter, inches....). By default, it's in mm.
2. retrieveMeasure(XYZ) and retrieveMeasure(XYZRGBA) will return a 4 channel float Mat. XYZRGBA will contain the RGBA color for the last float value (4 uchar (4*8b) <--> float (32b)) .
   Extraction will need to take into account the 4 channel : 

```
sl::zed::Mat mXYZmat= zed->retrieveMeasure(XYZ);
float* xyzBuffer = (float*) mXYZmat.data;
X =xyzBuffer [4*i+j*mdepth.step/sizeof(float)];
Y =xyzBuffer [4*i+j*mdepth.step/sizeof(float)+1];
Z =xyzBuffer [4*i+j*mdepth.step/sizeof(float)+2];

// for the color, in case you use XYZRGBA : 
float rgba_val =xyzBuffer [4*i+j*mdepth.step/sizeof(float)+3];
unsigned char* rgbaPixel = (unsigned char*) & rgba_val;

uchar r = rgbaPixel[0];
uchar g = rgbaPixel[1];
uchar b= rgbaPixel[2];
uchar a = rgbaPixel[3];

//

```

Best,

**Comment by deeplightanym** [comment]
Hi Oliver,

I am wondering why the white balance in XYZRGBA mode is so weird. The document says that I can change the value of White balance using setCameraSettingsValue but there is no WHITE_BALANCE constant. When I try to set Hue value, I get an exception in sl_zed64.dll

My SDK is version 1.1
System: win 10 64-bit, CUDA 8.0
When I use retrieveImage, it show normal color.

Best,
Vu

**Comment by obraun-sl** [comment]
Hi,
Can you show picture for XYZRGBA? 
I think it is a mistake in the documentation : you can modify the exposure, not the White Balance (which is automatic for now). 
Changing the Hue will impact as well the color balance. You should use those settings only in Live mode. (ZED SDK 1.2.0 fixes a bug in setCameraSettingsValue() when svo mode was activated).

I would recommend to update your ZED SDK version as well.

Best,
/*OB*/

**Comment by deeplightanym** [comment]
Hi Oliver,
I wrote some codes to analyse the video from SVO file. I need to retrieve both color image and position XYZ of some color markers. The following are my code to extract the color and XYZ, and the corresponding picture.

My code:
	sl::zed::Mat img = zed->retrieveMeasure(XYZRGBA);
	int* temColor = (int*)img.data;
	float* temPos = (float*)img.data;
	for (int i = 0; i < frameWidth * frameHeight; i++) {
		color[i] = temColor[i * 4 + 3];
		position[i * 3] = temPos[i * 4];
		position[i * 3 + 1] = temPos[i * 4 + 1];
		position[i * 3 + 2] = temPos[i * 4 + 2];
	}

retrieve LEFT image
![zedimageleft](https://cloud.githubusercontent.com/assets/10374204/20790914/848489dc-b7f5-11e6-8592-dac52c27de46.png)

extract from XYZRGBA
![zedwhitebalance](https://cloud.githubusercontent.com/assets/10374204/20790923/916d16dc-b7f5-11e6-8b2d-bf714be75d0e.png)

Thank you.
Vu

**Comment by yahiafarghaly** [comment]
Hi Oliver,
I have many questions,

Does `sl::zed::Mat mXYZmat= zed->retrieveMeasure(XYZ);` retrieve the x,y,z coordinates for a pixel in the current captured frame ? and if yes to which reference (where)?  

I tried the above code of your comment
```
//code 1
X =xyzBuffer [4*i+j*mdepth.step/sizeof(float)];
Y =xyzBuffer [4*i+j*mdepth.step/sizeof(float)+1];
Z =xyzBuffer [4*i+j*mdepth.step/sizeof(float)+2];
```
and i got sometimes negative values,why ? and the z value is not the same if i use this code

```
//code 2
sl::zed::Mat mdepth = zed->retrieveMeasure(DEPTH);
float* zBuffer = (float*) mdepth.data;
z =zBuffer[i+j*mdepth.step/sizeof(float)];
```
Despite the fact the "code 2" is giving more accurate result but sometimes cause a segmentation fault .(i am sure of the validity  of the i,j which is being indexed).


my other question , how you do this indexing in both cases (code 1 and code 2) ? where i can learn how you made it ?

finally, what's the best and more accurate way to retrieve pixel (X,Y,Z)? with which ZED params ? 

Thanks !

**Comment by yahiafarghaly** [comment]
@sl-braun 
another question,
 which camera is the depth is calculated right or left ? as reference

**Comment by obraun-sl** [comment]
Hi,

@eagletran : Use `zed->retrieveMeasure(XYZBGRA) `instead of `zed->retrieveMeasure(XYZRGBA);` Red and Blue channel seems flipped.

@yahiafarghaly 
* depth/Point cloud is mapped on the left image/sensor (Left is the reference)
* for XYZ extraction, I would do like this : 

0<i<width
0<j<height

```
          sl::zed::Mat cPointCloud= zed->retrieveMeasure(XYZRGBA);
          float x = ((float*)((uint8_t*)cPointCloud.data+j*cPointCloud.step))[4*i];
          float y = ((float*)((uint8_t*)cPointCloud.data+j*cPointCloud.step))[4*i+1];
          float z = ((float*)((uint8_t*)cPointCloud.data+j*cPointCloud.step))[4*i+2];
          float rgba =((float*)((uint8_t*)cPointCloud.data+j*cPointCloud.step))[4*i+3];
```

Or , For depth : 

```
        sl::zed::Mat data= zed->retrieveMeasure(DEPTH);
        float* ptr_line_data = (float*)((int8_t*)data->data +  j * data->step);
        float dist = ptr_line_data[i];
```

Basically, it's the "j" line extraction (using the step)  and then take the "i" column of the Mat.

Best,
/*OB*/

**Comment by deeplightanym** [comment]
Hi Oliver,
As you recommended, I upgrade my SDK to 1.2, but there may be some problems with the new SDK:
1) The VGA resolution never get to ~100Hz, it is very slow instead (~55Hz - ~75Hz). It works at ~60Hz correctly. (these numbers are in live-view mode, so no storage bottleneck effects). The SDK 1.1 can reach ~100Hz.
2) When I record the video with RAW mode, and play back (720 x 60Hz), the framerate is NA.

Can you tell me if these are bugs or intentional implementation? Do you have any suggestion to get the camera work at VGA 100Hz?
Thank you.

Best,
Vu

**Comment by obraun-sl** [comment]
Hi,

1. With DepthViewer or Explorer? (I mean with or without depth processing)
2. the RAW mode does not contains a recorded framerate (using timestamp). Only the lossless and lossy mode.

Best,
OB

**Comment by deeplightanym** [comment]
Hi Oliver,

I mean the Explorer only, without Depth processing.

Best,
Vu

**Comment by obraun-sl** [comment]
Hi,

It comes from the OpenGL rendering. In the new SDK1.2, the default gl format is sync to the display refresh rate (probably 60Hz).
To "remove" that clamp, go into your NVIDIA control panel (right click on the desktop) >> manage 3D settings. In the list, you will find an entry called "Vertical sync" : Set it to off to override the application parameters. You should reach 100Hz then.

(Assuming you are still on Windows, but same settings are available under Linux)

Best,
/*OB*/

**Comment by deeplightanym** [comment]
Hi Oliver,

Thank you for your support. It works at 100Hz now.

Best,
Vu

**Comment by obraun-sl** [comment]
Closing the issue, since it started to drift... ;)
